# Generated by Django 5.1 on 2026-06-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('host', models.CharField(max_length=255, verbose_name='Хост / IP')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='Порт')),
                ('status', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Статус')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('task_type', models.CharField(choices=[('ping', 'Пинг сервера'), ('disk_usage', 'Проверка диска'), ('memory_check', 'Проверка памяти'), ('custom_script', 'Пользовательский скрипт')], max_length=20, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failure', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
